[package]
name = "cub3d_rust"
version = "0.1.0"
edition = "2021"

#[profile.dev.package.'*']
#opt-level = 3

[profile.release]
lto = "fat"
debug = true
codegen-units = 1

[profile.bench]
debug = true

[dependencies]
macroquad = "0.3.25"
